version: '3.6'

services:
    thyme:
        image: self/thyme
        build: .
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - /etc/localtime:/etc/localtime:ro
            - ./data:/data
        environment:
            - DISPLAY=$DISPLAY
            - THYME_INTERVAL=${THYME_INTERVAL:-10}
            - THYME_STATS=${THYME_STATS:-false}
